version: '3'
services:
        app:
                build:
                        context: .
                        dockerfile: .docker/Dockerfile
                image: laravel-docker
                ports:
                        - 8080:80
